config/routes.rb
RentalCats::Application.routes.draw do

  resources :cats do
    resources :cat_rental_requests, only: [:new, :create, :index]
  end

  resources :users, only: [:new, :create, :show]

  post "/cat_rental_request/:id/approve", to: "cat_rental_requests#approve", as: "request_approve"
  post "/cat_rental_request/:id/deny", to: "cat_rental_requests#deny", as: "request_deny"

  resources :sessions

  # verb "/cats/:id/cat_rental_request/:id/deny", to: "controller#action", as: "helper"
  # get "/favorites", to: "users#favorites", as: "aslkdfjk"


end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  before_validation :default_values
  validates :start_date, :end_date, :cat_id, :user_id, :presence => true
  validates :status, :presence => true, inclusion: { in: %w(PENDING APPROVED DENIED), message: "not an ok status" }
  validate :no_overlaps

  belongs_to(:user)
  belongs_to(:cat)

  def approve!
    CatRentalRequest.transaction do
      self.status = "APPROVED"
      self.save!
      overlapping_pending_requests.each { |request| request.deny! }
    end
  end

  def deny!
    self.status = "DENIED"
    self.save!
  end

#  private

  def no_overlaps
    unless self.overlapping_approved_requests.empty? || self.status == "DENIED"
      errors[:base] << "Your rental timeframe has already been reserved!"
    end
  end

  def overlapping_requests
    # First, it has to grab all requests for the specified cat_id
    # Then, it compares the current requests start and end dates to see if it falls between any other request time period.
    CatRentalRequest.where(<<-SQL, {:cat_id => self.cat_id, :id => self.id, :start_date => self.start_date, :end_date => self.end_date})
    cat_rental_requests.cat_id = :cat_id
    AND ((:id IS NULL) OR (cat_rental_requests.id != :id))
    AND ((cat_rental_requests.start_date <= :end_date)
    AND (cat_rental_requests.end_date >= :start_date))
    SQL
  end

  def overlapping_pending_requests
    self.overlapping_requests.where("cat_rental_requests.status = 'PENDING'")
  end

  def overlapping_approved_requests
    self.overlapping_requests.where("cat_rental_requests.status = 'APPROVED'")
  end

  def default_values
    self.status ||= 'PENDING'
  end
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def new
    @cat_rental_request = CatRentalRequest.new
    render :new
  end

  def create
    @cat_rental_request = current_user.cat_rental_requests.new(cat_rental_request_params)
    if @cat_rental_request.save
      redirect_to cat_url(Cat.find(params[:cat_id]))
    else
      flash.now[:errors] = @cat_rental_request.errors.full_messages
      render :new
    end
  end

  def index
    redirect_to cats_url
  end

  def approve
    @cat_rental_request = CatRentalRequest.find(params[:id])
    if @cat_rental_request.cat.owner == current_user
      @cat_rental_request.approve!
      redirect_to cat_url(@cat_rental_request.cat)
    else
      flash[:errors] = ["You cannot approve a request for someone else's cat!"]
      redirect_to cat_url(@cat_rental_request.cat)
    end
  end

  def deny
    @cat_rental_request = CatRentalRequest.find(params[:id])
    if @cat_rental_request.cat.owner == current_user
      @cat_rental_request.deny!
      redirect_to cat_url(@cat_rental_request.cat)
    else
      flash[:errors] = ["You cannot approve a request for someone else's cat!"]
      redirect_to cat_url(@cat_rental_request.cat)
    end
  end

  private
  def cat_rental_request_params
      params.require(:@cat_rental_request).permit(
      :cat_id, :start_date, :end_date, :status
      )
  end
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/views/cat_rental_requests/new.html.erb
<form action="<%= cat_cat_rental_requests_url %>" method="POST">
<h1> File A Cat Rental Request Form 1040 </h1>

	<input
	     name="authenticity_token"
	     type="hidden"
	     value="<%= form_authenticity_token %>">


<% if flash.now[:errors] %>
	<% flash.now[:errors].each do |error| %>
		<%= error %>
	<% end %>
<% end %>
<br>
<label for="cat_id">Cat to be Rented</label>
	<select name="@cat_rental_request[cat_id]" id="cat_id">
		<% Cat.all.each do |cat| %>
			<option value=<%= cat.id %>><%= cat.name %></option>
		<% end %>
	</select>
	<br>
	<label for="rental_start_date">Rental Start Date</label>
	<input type="date" name="@cat_rental_request[start_date]" id="rental_start_date" value="<%= @cat_rental_request.start_date %>">
	<br>
	<label for="rental_end_date">Rental End Date</label>
	<input type="date" name="@cat_rental_request[end_date]" id="rental_end_date" value="<%= @cat_rental_request.end_date %>">
	<br>
	<input type="submit" value="File your request!">
</form>