config/routes.rb
RentalCats::Application.routes.draw do

  resources :cats do
    resources :cat_rental_requests, only: [:new, :create, :index]
  end

  resources :users, only: [:new, :create, :show]

  post "/cat_rental_request/:id/approve", to: "cat_rental_requests#approve", as: "request_approve"
  post "/cat_rental_request/:id/deny", to: "cat_rental_requests#deny", as: "request_deny"

  resources :sessions

  # verb "/cats/:id/cat_rental_request/:id/deny", to: "controller#action", as: "helper"
  # get "/favorites", to: "users#favorites", as: "aslkdfjk"


end

app/models/cat.rb
class Cat < ActiveRecord::Base
  COLORS = %w(orange brown white black yellow)

  validate :timeliness
  validates :color, inclusion: { in: COLORS,
    message: "not a valid color" }
  validates :sex, inclusion: { in: %w(M F),
    message: "not a good cat sex" }
  validates :birth_date, :color, :sex, :name, :description, :user_id, presence: :true

  has_many(:cat_rental_requests)

  belongs_to(:owner,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id
  )

  before_destroy :dependent => :destroy

  def age
    Date.today - self.birth_date
  end

  private

  def timeliness
    if self.birth_date && self.birth_date > Date.today
      errors[:birth_date] << "cat cannot be born in the future!"
    end
  end

end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  before_filter :require_ownership
  skip_before_filter :require_ownership, except: [:edit,:update]

  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = current_user.cats.new(cat_params)
    if @cat.save
      redirect_to cats_url
    end
  end

  def edit
    @cat = current_user.cats.find(params[:id])
    render :edit
  end

  def update
    @cat = current_user.cats.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end

  private
  def cat_params
    params.require(:cat).permit(
    :name, :color, :sex, :description, :birth_date
    )
  end

  def require_ownership
    if current_user.id!= Cat.find(params[:id]).user_id
      fail
      redirect_to cats_url
    end
  end
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/_form.html.erb
<% if @cat.persisted? %>
	<form action="<%= cat_url(@cat) %>" method="POST">

	<input type="hidden" name="_method" value="PATCH">
<% else %>
	<form action="<%= cats_url %>" method="POST">
<% end %>
		<input
		     name="authenticity_token"
		     type="hidden"
		     value="<%= form_authenticity_token %>">
	<label for="cat_name">Name</label>
	<input type="text" name="cat[name]" id="cat_name" value="<%= @cat.name %>">
	<br>
	<label for="cat_color">Coat Color</label>
	<select name="cat[color]" id="cat_color">
		<option selected><%= @cat.color %></option>
		<% Cat::COLORS.each do |color| %>
			<option value=<%= color %>><%= color %></option>
			<% end %>
	</select>
	<br>
	<input type="radio" name="cat[sex]" id="cat_sex_female" value="F" <%= "checked" if @cat.sex == "F" %>>
  <label for="cat_sex_female">Female</label>
  <input type="radio" name="cat[sex]" id="cat_sex_male" value="M" <%= "checked" if @cat.sex == "M" %>>
  <label for="cat_sex_male">Male</label>
	<br>
	<label for="cat_birth_date">Birth Date</label>
	<input type="date" name="cat[birth_date]" id="cat_birth_date" value="<%= @cat.birth_date %>">
	<br>
	<label for="cat_description">Description of Cat</label>
	<textarea name="cat[description]" id="cat_description"><%= @cat.description %></textarea>
<br><br>
<% if @cat.persisted? %>
	<input type="submit" value="change your cat - to a better cat or a worse cat">
<% else %>
	<input type="submit" value="Add your cat to the database!">
<% end %>
</form>

app/views/cats/edit.html.erb
<%= render "form", locals: {cat: @cat} %>

app/views/cats/index.html.erb
<h1>YAY CATS!</h1>
<ul><% @cats.each do |cat| %>
	<li><a href="<%= cat_url(cat) %>"><%= cat.name %></a></li>
	<% end %>
</ul>
<br>
<a href="<%= new_cat_url %>">Add a Cat to the Database!</a>

app/views/cats/new.html.erb
<!-- <form action="<%= cats_url %>" method="post">

	<label for="cat_name">Name</label>
	<input type="text" name="cat[name]" id="cat_name">
	<br>
	<label for="cat_color">Coat Color</label>
	<select name="cat[color]" id="cat_color">
		<option selected></option>
		<option value="orange">Orange</option>
		<option value="brown">Brown</option>
		<option value="white">White</option>
		<option value="black">Black</option>
		<option value="yellow">Yellow</option>
	</select>
	<br>
	<input type="radio" name="cat[sex]" id="cat_sex_female" value="F">
  <label for="cat_sex_female">Female</label>
  <input type="radio" name="cat[sex]" id="cat_sex_male" value="M">
  <label for="cat_sex_male">Male</label>
	<br>
	<label for="cat_birth_date">Birth Date</label>
	<input type="date" name="cat[birth_date]" id="cat_birth_date">
	<br>
	<label for="cat_description">Description of Cat</label>
	<textarea name="cat[description]" id="cat_description"></textarea>
<br><br>
	<input type="submit" value="make a new cat today"> -->


<%= render "form", locals: {cat: @cat} %>

app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>

<br>
<table>
	<tr>
		<td>Sex</td>
		<td><%= @cat.sex %></td>
	</tr>
	<tr>
		<td>Birthdate</td>
		<td><%= @cat.birth_date %></td>
	</tr>
	<tr>
		<td>Color</td>
		<td><%= @cat.color %></td>
	</tr>
	<tr>
		<td>Description</td>
		<td><%= @cat.description %></td>
	</tr>
</table>

<a href="<%= edit_cat_url(@cat) %>">Edit this Cat!</a>
<a href="<%= cats_url %>">Back to Cat Index</a>
<br>
<h3>Rental Requests</h3>
<table>
	<tr>
		<td> start date </td>
		<td> end date </td>
		<td> status </td>
	</tr>
	<% @cat.cat_rental_requests.order(:start_date).each do |request| %>
		<tr>
			<td><%= request.start_date %></td>
			<td><%= request.end_date %></td>
			<td><%= request.status%></td>
			<td><%= request.user.username %></td>
			<% if @cat.owner == current_user %>
			<td>
				<form action="<%= request_approve_url(request) %>" method="POST"><button type="submit">Approve!</button>
			<input
			     name="authenticity_token"
			     type="hidden"
			     value="<%= form_authenticity_token %>">

			</form></td>
			<td><form action="<%= request_deny_url(request) %>" method="POST"><button type="submit">Deny!</button>

			<input
			     name="authenticity_token"
			     type="hidden"
			     value="<%= form_authenticity_token %>">

			</form></td>
			<% end %>
		</tr>
	<% end %>
</table>
<a href="<%= new_cat_cat_rental_request_url(@cat) %>">Put in a Rental Request for this Cat!</a>